services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_typing_app
    volumes:
      - ./src/typinggame:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  web:
    image: nginx:alpine
    container_name: nginx3
    volumes:
      - ./src/typinggame:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8110:80"
    networks:
      - app-network
    depends_on:
      - db


  db:
    image: mysql:5.7
    container_name: mysql_db3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: typing
      MYSQL_USER: typing
      MYSQL_PASSWORD: password123
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3400:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin3
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8111:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local